# Generated by Django 3.1.1 on 2020-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0002_auto_20201217_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de fim')),
                ('estabelecimentos', models.ManyToManyField(to='gestao.Estabelecimento')),
            ],
        ),
    ]
