# Generated by Django 3.1.1 on 2020-12-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20201217_2242'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Vacinas')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.campanha')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ocupado', 'Ocupado'), ('Aplicada', 'Aplicada'), ('Disponível', 'Disponível')], default='Disponível', max_length=30, verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data de Vacinação')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.campanha')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estabelecimento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.paciente')),
            ],
        ),
    ]
