# Generated by Django 3.1.1 on 2020-12-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='lote',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Lote'),
        ),
    ]
