# Generated by Django 3.1.1 on 2020-12-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_estoque_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.estoque'),
        ),
    ]
