# Generated by Django 3.1.1 on 2020-12-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_aplicacao',
            field=models.DateTimeField(null=True, verbose_name='data_aplicacao'),
        ),
    ]
