# Generated by Django 3.1.1 on 2020-12-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20201217_2242'),
        ('agenda', '0005_agendamento_data_aplicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacinaPrivada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('estabelecimento', models.CharField(max_length=255, verbose_name='Estabelecimento de Aplicação')),
                ('data_vacinacao', models.DateField(null=True, verbose_name='Data de vacinação')),
                ('lote', models.CharField(max_length=255, verbose_name='Estabelecimento de Aplicação')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.campanha')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estabelecimento')),
                ('estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.estoque')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.paciente')),
            ],
        ),
    ]
