# Generated by Django 3.1.1 on 2020-12-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estado')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(help_text='Digite o CPF sem pontos ou traços.', max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informado')], default='N', max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('telefones', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefones')),
                ('celulares', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celulares')),
                ('email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email')),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.municipio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa Fisica',
                'verbose_name_plural': 'Pessoas Fisicas',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=12, unique=True, verbose_name='Código CNES')),
                ('nome', models.CharField(max_length=60)),
                ('razao_social', models.CharField(max_length=60, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, null=True, verbose_name='CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Logradouro')),
                ('num_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=40, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bairro')),
                ('data_ultima_atualizacao', models.DateTimeField(null=True, verbose_name='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.municipio')),
            ],
            options={
                'verbose_name': 'Estabelecimento de Saúde',
                'verbose_name_plural': 'Estabelecimentos de Saúde',
                'ordering': ['nome', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão Sus')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoafisica')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('pessoa_fisica', 'cartao_sus')},
            },
        ),
    ]
