# Generated by Django 3.1.1 on 2020-12-19 17:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        #('gestao', '0002_auto_20201217_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estado')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(help_text='Digite o CPF sem pontos ou traços.', max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informado')], default='N', max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('telefones', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefones')),
                ('celulares', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celulares')),
                ('email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email')),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.municipio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa Fisica',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=12, unique=True, verbose_name='Código CNES')),
                ('nome', models.CharField(max_length=60)),
                ('razao_social', models.CharField(max_length=60, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, null=True, verbose_name='CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Logradouro')),
                ('num_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=40, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bairro')),
                ('data_ultima_atualizacao', models.DateTimeField(null=True, verbose_name='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('prestador', models.BooleanField(default=False, verbose_name='Prestador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.municipio')),
            ],
            options={
                'verbose_name': 'Estabelecimento de Saúde',
                'verbose_name_plural': 'Estabelecimentos de Saúde',
                'ordering': ['nome', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='CoordenadorSus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estabelecimento')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoafisica')),
            ],
            options={
                'unique_together': {('pessoa_fisica', 'estabelecimento')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão Sus')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoafisica')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('pessoa_fisica', 'cartao_sus')},
            },
        ),
    ]
