# Generated by Django 3.1.1 on 2020-12-17 22:42

import pandas
from django.db import migrations
from django.conf import settings

def read_csv(filename, delimiter, **args):
    return pandas.read_csv(filename, sep=delimiter, **args)

def carregar_dados(apps, schema_editor):
    Municipio = apps.get_model('gestao', 'Municipio')
    Estado = apps.get_model('gestao', 'Estado')
    Estabelecimento = apps.get_model('gestao', 'Estabelecimento')

    file_path = f"{settings.BASE_DIR}/gestao/fixtures/municipios_ibge.csv"
    dados_estados_municipios = read_csv(file_path, ',')
    estados_set = set()

    for i, row in dados_estados_municipios.iterrows():
        estados_set.add((row['UF'], row['Nome_UF']))

    for x in estados_set:
        Estado.objects.create(codigo=x[0], nome=x[1])

    estados = Estado.objects.in_bulk(field_name='codigo')
    cidades = []

    for i, row in dados_estados_municipios.iterrows():
        cidades.append(
            Municipio(codigo=row['Codigo_Municipio'],
                        nome=row['Nome_Municipio'],
                        estado=estados[str(row['UF'])])
        )

    Municipio.objects.bulk_create(cidades)		

    file_path = f"{settings.BASE_DIR}/gestao/fixtures/estabelecimentos_saude.csv"
    estabelecimentos_saude = read_csv(file_path, ',', dtype={'NU_CNPJ': str})

    municipios = Municipio.objects.in_bulk(field_name='codigo')
    
    unidades = []
    for i, row in estabelecimentos_saude.iterrows():
        unidades.append(
            Estabelecimento(cnes=row['CO_CNES'], nome = row['NO_FANTASIA'],
                            razao_social = row['NO_RAZAO_SOCIAL'],
                            municipio=municipios[str(row['CO_MUNICIPIO_GESTOR'])],
                            logradouro=row['NO_LOGRADOURO'],
                            num_endereco=row['NU_ENDERECO'],
                            complemento=row['NO_COMPLEMENTO'],
                            bairro=row['NO_BAIRRO'], email=row['NO_EMAIL'],
                            cep=row['CO_CEP'], telefone=row['NU_TELEFONE'],
                            latitude=row['NU_LATITUDE'], longitude = row['NU_LONGITUDE'])
        )

    Estabelecimento.objects.bulk_create(unidades)		

    #call_command('importar_estados_municipios')
    #call_command('importar_estabelecimentos')

class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [migrations.RunPython(carregar_dados)]