# Generated by Django 3.1.1 on 2020-12-17 22:42

from django.db import migrations
from django.core.management import call_command

def carregar_dados(apps, schema_editor):
    call_command('importar_estados_municipios')
    call_command('importar_estabelecimentos')

class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [migrations.RunPython(carregar_dados)]