# Generated by Django 3.1.1 on 2020-12-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20201217_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='prestador',
            field=models.BooleanField(default=False, verbose_name='Prestador'),
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.estabelecimento')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoafisica')),
            ],
            options={
                'unique_together': {('pessoa_fisica', 'estabelecimento')},
            },
        ),
    ]
