# Generated by Django 3.1.1 on 2020-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20201218_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name': 'Pessoa Fisica'},
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
